feat: header,section anf footer added
mihrab34/NewsWeek-Clone pull request #2
Opened 2019-10-20 15:21 UTC by mihrab34

2019-11-08 02:43 UTC, imhta requested changes
# Changes required 🛑 
@mihrab34 you have done a good job but still there is few changes to address.

- In mobile version, the order of sections should be `Top Story`, `More Stories`, `Featured Stories` and then `Opinion`.
- In mobile version(Pixel 2 XL), There is a issue with navbar and sign in button. (To recreate this issue kindly open the website in chrome then `Ctrl`+`Shift`+`M`, then select Pixel 2 XL in devices list) 
![image](https://user-images.githubusercontent.com/25448577/68445267-6d48d780-01ff-11ea-8d63-f630062a4fb9.png)

- In mobile and tablet version, page is creating a horizontal scrolling issue, kindly check that. I think there is a issue with the sizing of the container.
![image](https://user-images.githubusercontent.com/25448577/68445293-80f43e00-01ff-11ea-9d4e-d60c9378da80.png)
#### Don't Forget to make another code review.
## Good luck
**Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

2019-11-12 17:41 UTC, shshamim63 commented
## Status :arrow_forward:  Changes Required :arrow_backward: 
___
Hi @mihrab34 :wave: ,
Awesome job on this project :clap: . I can see most of the items are rendering on the place that it should. Code looks nice and clean. But some issues are actually holding me to approve this project. I am sure that, you will cover them easily.
___
#### Please follow the instructions below :point_down:  to complete the project.
___
### :clubs: Mandatory Changes :clubs: 
___
1. On the mobile view the nav item is breaking down. Which is actually catching my eye. Inspect the element and you will get the way to fix it.
![news1](https://user-images.githubusercontent.com/38625956/68695264-e8fea780-05a4-11ea-8511-741e9e4e2706.png)
2. On the header-top class at your css line no. 428, I can see a !important. Is it possible to remove it?
___
### :spades: Optional Changes :spades: 
___
1. On tab view the marked section looks too big. I think if you make this section smaller it will look more beautiful.
![news2](https://user-images.githubusercontent.com/38625956/68695599-8eb21680-05a5-11ea-9ae4-e75e148f2089.png)
___
### Please follow the instructions above :point_up: and send another code review request.
___
## :herb:  Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

2019-11-15 08:18 UTC, suretrust requested changes
Hi @mihrab34,

### Great job thus far on the project. :raised_hands:  Just a few suggestions to wrap it up:

- [ ] Please see my comment on your code.

- [ ] You used Git flow as opposed to the GitHub flow requirement. See [this article](https://www.freshconsulting.com/git-development-workflows-git-flow-vs-github-flow/) to understand the difference.

- [ ] In mobile view, let's arrange the sections in the correct order, `Top story` => `More stories` => `Culture and travel` => `Featured stories` => `Opinion` => `Latest news`. You can achieve this using bootstrap's `order` class.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-11-15 08:18 UTC, suretrust commented on index.html
> +          </div>
On medium screen, the editor's picks section should have 2 columns. Please refer to the images below:

![editor](https://user-images.githubusercontent.com/31304943/68927157-6bdf5800-0787-11ea-976c-9a5e7b80c83f.png)
![editor2](https://user-images.githubusercontent.com/31304943/68927158-6c77ee80-0787-11ea-9a83-000fadd98698.png)

2019-11-15 18:21 UTC, merged